In [4]:
import numpy as np
from sklearn import datasets 
import keras
from keras import layers

In [6]:
digits= datasets.load_digits()
xs= digits['data']
xs.shape

(1797, 64)

In [7]:
L0= layers.Input((64,))
L1= layers.Dense(32, activation='relu')(L0)
L2= layers.Dense(16, activation='relu')(L1)
L3= layers.Dense(8, activation='relu')(L2)
Latent= layers.Dense(4, activation='relu')(L3) # latent space
L4= layers.Dense(8, activation='relu')(Latent)
L5= layers.Dense(16, activation='relu')(L4)
L6= layers.Dense(32, activation='relu')(L5)
L7= layers.Dense(64, activation='relu')(L6)

In [8]:
encoder= keras.models.Model(L0, Latent)
decoder= keras.models.Model(Latent, L7)
autoencoder= keras.models.Model(L0,L7)

In [12]:
opt= keras.optimizers.Adamax(learning_rate=.01)
autoencoder.compile(loss='mae', optimizer=opt)

In [13]:
autoencoder.fit(xs,xs, epochs=100, validation_split=.05) # input=output

Epoch 1/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 3.7561 - val_loss: 3.3404
Epoch 2/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.1734 - val_loss: 3.0446
Epoch 3/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.9590 - val_loss: 2.9860
Epoch 4/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.9072 - val_loss: 2.9304
Epoch 5/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.8337 - val_loss: 2.7346
Epoch 6/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.6822 - val_loss: 2.5573
Epoch 7/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.5239 - val_loss: 2.5293
Epoch 8/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.5013 - val_loss: 2.5167
Epoch 9/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.4406 - val_loss: 2.4843
Epoch 10/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.4032 - val_loss: 2.4395
Epoch 11/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.3599 - val_loss: 2.4363
Epoch 12/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.3

In [14]:
code= encoder.predict(xs[:1])
code

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[64.19792 , 16.91451 ,  9.508382,  0.      ]], dtype=float32)

In [15]:
decoder.predict(code)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[ 0.       ,  0.       ,  5.0116353, 12.769773 , 12.447477 ,
         5.125451 ,  0.       ,  0.       ,  0.       ,  0.       ,
        12.738414 , 12.202764 , 10.1023855, 13.407299 ,  0.       ,
         0.       ,  0.       ,  2.511332 , 13.8510475,  4.4457593,
         0.       , 11.885617 ,  0.       ,  0.       ,  0.       ,
         0.       , 13.167093 ,  1.0168526,  0.       ,  9.971049 ,
         0.       ,  0.       ,  0.       ,  5.847256 , 10.888031 ,
         0.       ,  0.       , 10.712683 ,  6.7845445,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        13.417434 ,  1.954971 ,  0.       ,  0.       ,  0.       ,
         0.       ,  8.113926 , 11.404037 , 11.218484 ,  0.       ,
         0.       ,  0.       ,  0.       ,  5.878082 , 13.848377 ,
        11.225514 ,  0.6375505,  0.       ,  0.       ]], dtype=float32)

In [16]:
autoencoder.predict(xs[:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


array([[ 0.       ,  0.       ,  5.0116353, 12.769773 , 12.447477 ,
         5.125451 ,  0.       ,  0.       ,  0.       ,  0.       ,
        12.738414 , 12.202764 , 10.1023855, 13.407299 ,  0.       ,
         0.       ,  0.       ,  2.511332 , 13.8510475,  4.4457593,
         0.       , 11.885617 ,  0.       ,  0.       ,  0.       ,
         0.       , 13.167093 ,  1.0168526,  0.       ,  9.971049 ,
         0.       ,  0.       ,  0.       ,  5.847256 , 10.888031 ,
         0.       ,  0.       , 10.712683 ,  6.7845445,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        13.417434 ,  1.954971 ,  0.       ,  0.       ,  0.       ,
         0.       ,  8.113926 , 11.404037 , 11.218484 ,  0.       ,
         0.       ,  0.       ,  0.       ,  5.878082 , 13.848377 ,
        11.225514 ,  0.6375505,  0.       ,  0.       ]], dtype=float32)

In [ ]:
# autoencoder = decoder(encoder) !